apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
  namespace: my-django-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
      - name: celery
        image: my-django-app:latest
        command: ["celery", "-A", "myapp", "worker", "--loglevel=info"]
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: REDIS_HOST
