apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-backend
  namespace: my-django-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-backend
  template:
    metadata:
      labels:
        app: django-backend
    spec:
      containers:
      - name: django
        image: my-django-app:latest
        env:
        - name: DJANGO_SETTINGS_MODULE
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: DJANGO_SETTINGS_MODULE
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: DATABASE_PASSWORD
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: static-volume
          mountPath: /app/static
        - name: media-volume
          mountPath: /app/media
      volumes:
      - name: static-volume
        persistentVolumeClaim:
          claimName: pvc-static
      - name: media-volume
        persistentVolumeClaim:
          claimName: pvc-media
