apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: my-django-app
spec:
  selector:
    app: django-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
