apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-static
  namespace: my-django-app
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /mnt/data/static
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-media
  namespace: my-django-app
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /mnt/data/media
