apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  namespace: my-django-app
type: Opaque
data:
  DATABASE_PASSWORD: cGFzc3dvcmQ=  # base64 for "password"
  SECRET_KEY: c2VjcmV0X2tleQ==     # base64 for "secret_key"
